// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/add-transaction.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function getEnv(name) {
  const g = globalThis;
  const denoVal = g?.Deno?.env?.get?.(name);
  if (denoVal) return denoVal;
  const procVal = g?.process?.env?.[name];
  if (procVal) return procVal;
  throw new Error(`Missing env ${name}`);
}
function supabaseForUser(ctx) {
  const url = getEnv("SUPABASE_URL");
  let key;
  try {
    key = getEnv("SUPABASE_ANON_KEY");
  } catch {
    key = getEnv("SUPABASE_PUBLISHABLE_KEY");
  }
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/add-transaction.ts
var add_transaction_default = defineTool({
  name: "add_transaction",
  title: "Add transaction",
  description: "Add an income, expense, or investment transaction for the signed-in user. Amount is positive; type distinguishes direction. For investments, provide investment_type and investment_operation.",
  inputSchema: {
    type: z.enum(["income", "expense", "investment"]).describe("Transaction type."),
    amount: z.number().positive().describe("Positive numeric amount in BRL."),
    category: z.string().min(1).describe("Category slug (e.g. alimentacao, transporte, salario, freelance, outros_despesa, outros_receita)."),
    description: z.string().optional().describe("Free-text description."),
    transaction_date: z.string().describe("Date YYYY-MM-DD."),
    institution: z.string().optional().describe("Institution / broker (investments)."),
    investment_type: z.enum(["cdb", "tesouro_direto", "acoes", "fii", "criptomoedas", "previdencia", "poupanca", "etf", "renda_fixa", "outros"]).optional().describe("Required when type=investment."),
    investment_operation: z.enum(["deposit", "withdraw", "yield", "loss"]).optional().describe("Required when type=investment.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (input.type === "investment" && (!input.investment_type || !input.investment_operation)) {
      return {
        content: [{ type: "text", text: "investment_type and investment_operation are required for investments" }],
        isError: true
      };
    }
    const { data, error } = await supabaseForUser(ctx).from("transactions").insert({
      user_id: ctx.getUserId(),
      type: input.type,
      amount: input.amount,
      category: input.category,
      description: input.description ?? null,
      transaction_date: input.transaction_date,
      institution: input.institution ?? null,
      investment_type: input.investment_type ?? null,
      investment_operation: input.investment_operation ?? null,
      source: "mcp"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created transaction ${data.id}` }],
      structuredContent: { transaction: data }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's financial transactions (income, expense, investment), most recent first. Optionally filter by type, category, or date range (YYYY-MM-DD).",
  inputSchema: {
    type: z2.enum(["income", "expense", "investment"]).optional().describe("Filter by transaction type."),
    category: z2.string().optional().describe("Filter by category slug (e.g. alimentacao, salario)."),
    from: z2.string().optional().describe("Start date inclusive, YYYY-MM-DD."),
    to: z2.string().optional().describe("End date inclusive, YYYY-MM-DD."),
    limit: z2.number().int().positive().max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, category, from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("transactions").select("id, type, amount, category, description, transaction_date, institution, investment_type, investment_operation").eq("user_id", ctx.getUserId()).order("transaction_date", { ascending: false }).limit(limit ?? 50);
    if (type) q = q.eq("type", type);
    if (category) q = q.eq("category", category);
    if (from) q = q.gte("transaction_date", from);
    if (to) q = q.lte("transaction_date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/delete-transaction.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var delete_transaction_default = defineTool3({
  name: "delete_transaction",
  title: "Delete transaction",
  description: "Delete one of the signed-in user's transactions by id.",
  inputSchema: {
    id: z3.string().uuid().describe("Transaction id to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { error } = await supabaseForUser(ctx).from("transactions").delete().eq("user_id", ctx.getUserId()).eq("id", id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Deleted ${id}` }] };
  }
});

// src/lib/mcp/tools/get-financial-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var get_financial_summary_default = defineTool4({
  name: "get_financial_summary",
  title: "Get financial summary",
  description: "Aggregate the signed-in user's income, expenses, investments and net balance across an optional date range.",
  inputSchema: {
    from: z4.string().optional().describe("Start date inclusive, YYYY-MM-DD."),
    to: z4.string().optional().describe("End date inclusive, YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser(ctx).from("transactions").select("type, amount, category, investment_operation").eq("user_id", ctx.getUserId());
    if (from) q = q.gte("transaction_date", from);
    if (to) q = q.lte("transaction_date", to);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    let income = 0;
    let expenses = 0;
    const inv = { deposits: 0, withdraws: 0, yields: 0, losses: 0 };
    const byCategory = {};
    for (const r of rows) {
      const amt = Number(r.amount) || 0;
      if (r.type === "income") {
        income += amt;
      } else if (r.type === "expense") {
        expenses += amt;
        byCategory[r.category] = (byCategory[r.category] ?? 0) + amt;
      } else if (r.type === "investment") {
        if (r.investment_operation === "deposit") inv.deposits += amt;
        else if (r.investment_operation === "withdraw") inv.withdraws += amt;
        else if (r.investment_operation === "yield") inv.yields += amt;
        else if (r.investment_operation === "loss") inv.losses += amt;
      }
    }
    const summary = {
      period: { from: from ?? null, to: to ?? null },
      income,
      expenses,
      net: income - expenses,
      investments: inv,
      expenses_by_category: byCategory,
      transaction_count: rows.length
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "arqzquiibhfddjhcpxxk";
var mcp_default = defineMcp({
  name: "finbot-mcp",
  title: "FinBot",
  version: "0.1.0",
  instructions: "Tools for the FinBot personal finance app. Use `list_transactions` to inspect recent activity, `add_transaction` to record income/expenses/investments (amount is always positive; direction comes from `type`), `delete_transaction` to remove an entry by id, and `get_financial_summary` for aggregated income/expenses/investments over a period. Categories and dates follow the BR conventions used in the app (dates YYYY-MM-DD).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_transactions_default, add_transaction_default, delete_transaction_default, get_financial_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
